import { COMPONENTS } from './enums';

const itemGilValues = {
  [COMPONENTS.CREDIT_CHIP]: 500,
  [COMPONENTS.WICKED_FANG]: 40,
  [COMPONENTS.POLYMER_EMULSION]: 100,
  [COMPONENTS.DIGITAL_CIRCUIT]: 230,
  [COMPONENTS.CHIPPED_FANG]: 15,
  [COMPONENTS.TORN_LEATHER]: 15,
  [COMPONENTS.THICKENED_HIDE]: 40,
  [COMPONENTS.CIETH_TEAR]: 15,
  [COMPONENTS.TEAR_OF_FRUSTRATION]: 40,
  [COMPONENTS.BEGRIMED_CLAW]: 15,
  [COMPONENTS.BESTIAL_CLAW]: 40,
  [COMPONENTS.PARAFFIN_OIL]: 160,
  [COMPONENTS.SPARK_PLUG]: 160,
  [COMPONENTS.PASSIVE_DETECTOR]: 420,
  [COMPONENTS.SHATTERED_BONE]: 15,
  [COMPONENTS.STURDY_BONE]: 40,
  [COMPONENTS.ELECTROLYTIC_CAPACITOR]: 160,
  [COMPONENTS.CERAMIC_ARMOR]: 330,
  [COMPONENTS.BOMB_ASHES]: 90,
  [COMPONENTS.BOMB_FRAGMENT]: 215,
  [COMPONENTS.GUMMY_OIL]: 15,
  [COMPONENTS.FRAGRANT_OIL]: 40,
  [COMPONENTS.TURBOJET]: 420,
  [COMPONENTS.SUPERCONDUCTOR]: 420,
  [COMPONENTS.INCENTIVE_CHIP]: 2500,
  [COMPONENTS.ABOMINABLE_WING]: 75,
  [COMPONENTS.URANINITE]: 5000,
  [COMPONENTS.GYROSCOPE]: 330,
  [COMPONENTS.PIEZOELECTRIC_ELEMENT]: 420,
  [COMPONENTS.SILICONE_OIL]: 320
}

export const getComponentGilValue = item_name => itemGilValues[item_name]
